### ISSUE TITLE
Add CNAME to DNS

### ISSUE THREAD

**Issue by vmbrasseur** [IAS3Perl/ias3perl.github.io#1]
@StylusEater added a CNAME file to the repo (thank you!), but there now needs to be a DNS entry added at the registrar end.

The name is registered to me, so I'll handle this.

[Instructions](https://help.github.com/articles/tips-for-configuring-an-a-record-with-your-dns-provider/)

**Comment by vmbrasseur** [comment]
Added: A records for 192.30.252.154 and 192.30.252.153 for ias3perl.org.

```
Trimalchio:~ brasseur$ dig ias3.com +nostats +nocomments +nocmd

; <<>> DiG 9.8.3-P1 <<>> ias3.com +nostats +nocomments +nocmd
;; global options: +cmd
;ias3.com.          IN  A
ias3.com.       14400   IN  A   94.228.218.40
```

Current status: waiting for the goodies to propagate.

**Comment by vmbrasseur** [comment]
What helps: using the correct domain:

```
Trimalchio:~ brasseur$ dig ias3perl.org +nostats +nocomments +nocmd

; <<>> DiG 9.8.3-P1 <<>> ias3perl.org +nostats +nocomments +nocmd
;; global options: +cmd
;ias3perl.org.          IN  A
ias3perl.org.       10800   IN  SOA ns1.dreamhost.com. hostmaster.dreamhost.com. 2015061601 19663 1800 1814400 14400
```

And now, boom, http://ias3perl.org resolves correctly.

@StylusEater, could you please confirm on your end before I close this issue?

**Comment by StylusEater** [comment]
Fixed.

**Comment by StylusEater** [comment]
Closing.
